# Generated by Django 5.0.4 on 2026-07-07 03:26

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título de la Actividad/Aviso')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Detalle de la Actividad')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='alumnos/%Y/%m/%d/', verbose_name='Imagen Opcional')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Actividad de Alumno',
                'verbose_name_plural': 'Actividades de Alumnos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
