# Generated by Django 5.0.4 on 2026-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('resumen', models.CharField(max_length=300)),
                ('contenido_completo', models.TextField(verbose_name='Información Detallada')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='carreras/')),
            ],
        ),
    ]
