# Generated by Django 5.0.4 on 2026-06-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carreras/galeria/', verbose_name='Imagen adicional')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta (Opcional)')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='carreras.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
    ]
