# Generated by Django 5.0.4 on 2026-07-01 02:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_imagencarrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='contenido_completo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Información Detallada'),
        ),
    ]
